INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 0, 'Demonstration');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 1, 'Demonstration (unspezifisch)');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 3, 'Go-In');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 7, 'Fahrraddemonstration');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 2, 'Kundgebung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 8, 'Menschenkette');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 4, 'Sit-In');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 5, 'Sleep-In');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(1, 6, 'Traktordemonstration');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 8, 'Anhörung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 4, 'Einspruchsfrist');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 3, 'Erörterungstermin');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 0, 'Juristische Auseinandersetzung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 5, 'Juristisches Verbot einer Aktivität');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 7, 'Kündigung (beruflich)');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 1, 'Prozeß gegen Bewegungsaktivisten');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 2, 'Prozeß von Bewegungsaktivisten');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 6, 'Räumungsklage, Wohnungskündigung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(2, 9, 'Verurteilung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(3, 0, 'Legislative Aktivitäten');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(3, 1, 'Lesung / Verabschiedung eines Gesetzes');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(3, 2, 'Parlaments-, Gemeinderatsdebatte');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(4, 3, 'Abhöraktion');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(4, 5, 'Abschiebung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(4, 2, 'Festnahme, Verhaftung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(4, 1, 'Hausdurchsuchung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(4, 0, 'Maßnahmen der Exekutive');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(4, 4, 'Räumung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(5, 2, 'Aufstand, Revolution');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(5, 1, 'Krieg');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(5, 0, 'Militärische Auseinandersetzung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(5, 3, 'Putsch');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(6, 3, 'Gründungsversammlung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(6, 0, 'Gruppen-, Vereinstreffen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(6, 1, 'Gruppensitzung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(6, 2, 'Mitgliederversammlung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 8, 'Ausstellung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 4, 'Bürgerversammlung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 9, 'Diskussionsveranstaltung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 5, 'Informationsveranstaltung, Teach-In');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 1, 'Kongreß');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 0, 'Öffentliche Versammlungen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 7, 'Plenum');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 2, 'Tagung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 6, 'Veranstaltungsreihe');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(7, 3, 'Vollversammlung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(8, 0, 'Besetzungen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(8, 3, 'Blockade');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(8, 1, 'Hausbesetzung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(8, 2, 'Platzbesetzung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 1, 'Attentat');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 8, 'Ausbruch');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 5, 'Banküberfall');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 3, 'Brand-, Bombenanschlag');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 7, 'Brandanschlag');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 2, 'Entführung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 6, 'Gefangenenbefreiung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 9, 'Geiselname');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 0, 'Militante Aktionen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(9, 4, 'Straßenschlacht');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 4, '"wilder" Streik');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 5, 'Boykott');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 2, 'gewerkschaftlicher Streik');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 3, 'gewerkschaftlicher Warnstreik');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 6, 'Hungerstreik');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 0, 'Streiks, Boykotte');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(10, 1, 'Uni-Streik');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(11, 5, 'Atom-, Gitfmülltransport');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(11, 1, 'Chemieunfall');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(11, 0, 'Katastrophen, Skandale');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(11, 4, 'Müllskandal');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(11, 3, 'Ölpest, Meeresverschmutzung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(11, 2, 'Reaktorkatastrophe');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 7, 'Fernsehbeitrag');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 1, 'Flugblattveröffentlichung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 8, 'Offener Brief');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 12, 'Öffentliche Erklärung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 10, 'Plakataktion');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 4, 'Pressekonferenz');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 5, 'Pressemitteilung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 0, 'Publizistische Aktivität');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 6, 'Radiosendung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 11, 'Unterschriftenliste');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 2, 'Veröffentlichung einer Broschüre');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 3, 'Veröffentlichung einer Zeitschrift');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(12, 9, 'Veröffentlichung eines Beschlusses/Gesetzes');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 7, 'Café');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 6, 'Fest');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 3, 'Filmvorführung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 1, 'Konzert');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 0, 'Kulturelle Aktivitäten');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 5, 'Kunstausstellung');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 4, 'Performance');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 9, 'Radiosendung (kulturell)');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 2, 'Theater');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(13, 8, 'Workshop');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(14, 1, 'Bundestagswahlen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(14, 3, 'Gemeinderatswahlen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(14, 2, 'Landtagswahlen');
INSERT INTO ereignistyp (haupt, unter, beschreibung) VALUES(14, 0, 'Wahlen');
